apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret-nfs
type: Opaque
data:
  username: YWRtaW4= #admin | using base64
  password: YWRtaW4= #admin | using base64

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-nfs
spec:
  selector:
    app: mongodb-nfs
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32789
  type: NodePort

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc-nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: "truenas-nfs-csi"
spec:
  storageClassName: truenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-nfs
  template:
    metadata:
      labels:
        app: mongodb-nfs
    spec:
      containers:
      - name: mongodb-nfs
        image: mongo:5.0
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret-nfs
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret-nfs
              key: password
        volumeMounts:
        - name: mongodb-data
          mountPath: "/data/db"
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc-nfs
