apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret-iscsi
  namespace: quota-pod-example
type: Opaque
data:
  username: YWRtaW4= #admin | using base64
  password: YWRtaW4= #admin | using base64

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-iscsi
  namespace: quota-pod-example
spec:
  selector:
    app: mongodb-iscsi
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32788
  type: NodePort

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc-iscsi
  namespace: quota-pod-example
  annotations:
    volume.beta.kubernetes.io/storage-class: "truenas-iscsi-csi"
spec:
  storageClassName: truenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-iscsi
  namespace: quota-pod-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-iscsi
  template:
    metadata:
      labels:
        app: mongodb-iscsi
    spec:
      containers:
      - name: mongodb-iscsi
        image: mongo:5.0
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret-iscsi
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret-iscsi
              key: password
        volumeMounts:
        - name: mongodb-data
          mountPath: "/data/db"
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc-iscsi
      