---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "395ed071-3ca7-4467-ac30-8da8061057d3",
        "monitors": [
          "10.10.10.221:6789",
          "10.10.10.222:6789",
          "10.10.10.223:6789",
          "10.10.10.224:6789",
          "10.10.10.225:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
  namespace: ceph
