apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret-ceph
type: Opaque
data:
  username: YWRtaW4= #admin | using base64
  password: YWRtaW4= #admin | using base64

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-ceph
spec:
  selector:
    app: mongodb-ceph
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32788
  type: NodePort

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc-ceph
  annotations:
    volume.beta.kubernetes.io/storage-class: "csi-rbd-sc"
spec:
  storageClassName: csi-rbd-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-ceph
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-ceph
  template:
    metadata:
      labels:
        app: mongodb-ceph
    spec:
      containers:
      - name: mongodb-ceph
        image: mongo:5.0
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret-ceph
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret-ceph
              key: password
        volumeMounts:
        - name: mongodb-data
          mountPath: "/data/db"
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc-ceph
      
